### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by StarTrix28** [tobspr/RenderPipeline#128]
Traceback (most recent call last):
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\main.py", line 314, in <module>
    w = World().run()
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\main.py", line 70, in __init__
    self.render_pipeline.create(self)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rpcore\render_pipeline.py", line 159, in create
    self._init_showbase(base)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rpcore\render_pipeline.py", line 480, in _init_showbase
    self.pre_showbase_init()
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rpcore\render_pipeline.py", line 139, in pre_showbase_init
    self.load_settings("/$$rpconfig/pipeline.yaml")
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rpcore\render_pipeline.py", line 95, in load_settings
    self.settings = load_yaml_file_flat(path)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\__init__.py", line 62, in load_yaml_file_flat
    return __flatten(load_yaml_file(filename))
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\__init__.py", line 32, in load_yaml_file
    parsed_yaml = yaml_load(handle, Loader=SafeLoader)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Latitude E 7440\Desktop\RenderPipeline-master\samples\02-Roaming-Ralph\../..\rplibs\yaml\yaml_py3\constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

Sample: Roaming Ralph
OS: Windows 10
Python: 3.10.1

original version of Roaming Ralph work normally 
#collections couldn't be installed becouse there is no compatible version

**Comment by Tusnad30** [comment]
Replace collections.Hashable with collections.abc.Hashable at line 126 in rplibs\yaml\yaml_py3\constructor.py
