### ISSUE TITLE
GL_INVALID_VALUE and GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by nickmaleki** [tobspr/RenderPipeline#136]
Since upgrading to Panda3D 1.11.0, so I can use M_relative, I am not able to use RenderPipeline. I get the attached error: 
```
[>] RenderPipeline            Finished initialization in 7.786 s, first frame: 3 
DCFile::read of /c/Users/xnick/Downloads/render_pipeline/samples/direct.dc
DCFile::read of /c/Users/xnick/Downloads/render_pipeline/samples/Starcel/sample.dc
[>] RenderPipeline            Took 0.094 s until first frame 
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-LightData
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-ShadowSourceData
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-CommandQueue
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-CellList
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-FrustumLights
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-VisibleLightCount
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-PerCellLightCounts
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-PerCellLights
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-GroupedPerCellLights
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-GroupedPerCellLightsCount
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-PerCellProbes
:display:gsg:glgsg(error): GL_INVALID_VALUE error generated. Invalid image format.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-EnvmapData
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
Assertion failed: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:display:gsg:glgsg(error): Could not load ImgBuffer-ExposureStorage
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. Target doesn't match the texture's target.
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. The target of the texture named by <texture> and the target <textarget> do not match.
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\direct\showbase\ShowBase.py", line 2250, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
:task(error): Exception occurred in PythonTask igLoop
Traceback (most recent call last):
  File "C:\Users\xnick\Downloads\render_pipeline\samples\Starcel\client.py", line 776, in <module>
    MainApp().run()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\ShowBase.py", line 3440, in run
    self.taskMgr.run()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 629, in run
    self.step()
  File "C:\Panda3D-1.11.0-x64\direct\task\Task.py", line 579, in step
    self.mgr.poll()
  File "C:\Panda3D-1.11.0-x64\direct\showbase\ShowBase.py", line 2250, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: !gtc->_immutable at line 14583 of C:\Users\xnick\Downloads\panda3d-master (2)\panda3d-master\panda\src\glstuff\glGraphicsStateGuardian_src.cxx
[>] MountManager              Cleaning up .. 

Process finished with exit code 1
```

**Comment by rdb** [comment]
Is gl-immutable-texture-storage set to true in Config.prc?

**Comment by nickmaleki** [comment]
in `/config/panda3d-config.prc` `gl-immutable-texture-storage` is `#t`

**Comment by rdb** [comment]
This is probably a regression in Panda3D, see panda3d/panda3d#1602
