### ISSUE TITLE
GLSL 4.30 is not supported

### ISSUE THREAD

**Issue by minecraft2048** [tobspr/RenderPipeline#76]
Panda3D version: 1.10 self compiled from git clone with Python 3.6.0
OS: Arch Linux
GPU: Laptop with Intel i7 integrated GPU and Nvidia GTX 960m, open source driver for Intel and Nvidia proprietary driver 378.13  

Panda3d compilation output:

```
feanor@silmaril ~/D/P/panda3d> python makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2
/bin/sh: rpm: command not found
/bin/sh: rpm: command not found
Version: 1.10.0
Using Python 3.6
Target arch: x86_64
WARNING: Could not locate thirdparty package artoolkit, excluding from build
WARNING: Could not locate thirdparty package fcollada, excluding from build
WARNING: Could not locate thirdparty package assimp, excluding from build
WARNING: Could not locate thirdparty package fftw, excluding from build
WARNING: Could not locate thirdparty package fmodex, excluding from build
WARNING: Could not locate thirdparty package ode, excluding from build
WARNING: Could not locate thirdparty package squish, excluding from build
WARNING: Could not locate thirdparty package vrpn, excluding from build
WARNING: Could not locate thirdparty package opencv, excluding from build
WARNING: Could not locate thirdparty package rocket, excluding from build
Generating dependencies...
[100%] Building installer
Storing dependency cache.
Elapsed Time: 3 sec
To build an installer, either rpmbuild or dpkg-deb must be present on your system!
Build terminated.
feanor@silmaril ~/D/P/panda3d> ls
```

RenderPipeline setup.py output:
```
feanor@silmaril ~/D/P/RenderPipeline> python setup.py
-------------------------------------------------------------------------------

Render Pipeline Setup 1.3

-------------------------------------------------------------------------------


[ 01 ]  Checking Panda3D Modules


[ 02 ]  Checking requirements ..
	Running script: data/setup/check_requirements.py
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started


The C++ modules of the pipeline are faster and produce better 
results, but we will have to compile them. As alternative, 
a Python fallback is used, which is slower and produces worse 
results. Also some plugins only partially work with the python 
fallback (e.g. PSSM). Do you want to compile the C++ modules? (y/n): y


[ 03 ]  Downloading the module builder ...
	Running script: rpcore/native/update_module_builder.py


[ 04 ]  Building the native code .. (This might take a while!)
	Running script: rpcore/native/build.py


[ 05 ]  Generating .txo files ...
	Running script: data/generate_txo_files.py
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started


[ 06 ]  Filtering default cubemap ..
	Running script: data/default_cubemap/filter.py
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader filter.compute.glsl:
filter.compute.glsl:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
filter.compute.glsl:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10
Assertion failed: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Traceback (most recent call last):
  File "filter.py", line 105, in <module>
    Application()
  File "filter.py", line 93, in __init__
    dest_cubemap.write(join(filter_dir, "{}-#.png".format(mipmap)), 0, 0, True, False)
AssertionError: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Failed to execute 'filter.py'
Output: Command '['/usr/bin/python', '-B', 'filter.py']' returned non-zero exit status 1. 
 Filtering mipmap 0
 Extracting data ..
 Writing data ..




It seems the setup failed, do you want to open the troubleshooting page for this step? (y/n): y
OK, opening https://github.com/tobspr/RenderPipeline/wiki/Setup-Troubleshooting#filtering-default-cubemap 


Setup failed:	 Python script didn't return properly!

Please fix the above errors and then restart the setup.

feanor@silmaril ~/D/P/RenderPipeline>    
```

Now why do the `filter.compute.glsl` says `error: GLSL 4.30 is not supported` and ` error: Compute shaders require GLSL 4.30' ?

**Comment by minecraft2048** [comment]
Found this issue: https://github.com/tobspr/RenderPipeline/issues/75 and it turns out that Intel does not support compute shader, so I need to use Nvidia card. As this is Linux, @rdb solution does not apply, as Linux uses bumblebee and primusrun to switch applications to use Nvidia. 

Running `primusrun setup.py` does not work, as that does not ensure that the problematic data/default_cubemap/filter.py runs under Nvidia. To solve this problem, the setup.py function exec_python_file need to be modified:

```
def exec_python_file(pth, args=None, troubleshoot=None):
    """ Executes a python file and checks the return value """
    basedir = os.path.dirname(os.path.abspath(os.path.join(SETUP_DIR, pth))) + "/"
    print("\tRunning script:", Fore.YELLOW + Style.BRIGHT + pth + Style.RESET_ALL)
    pth = os.path.basename(pth)
    os.chdir(basedir)
    cmd = ["primusrun",sys.executable, "-B", pth] + (args or [])
    if CMD_ARGS.verbose:
        print("Executing", ' '.join(cmd))
        print("CWD is", basedir)
    try:
        output = subprocess.check_output(cmd, stderr=sys.stderr)
    except subprocess.CalledProcessError as msg:
        print(color("Failed to execute '" + pth + "'", Fore.YELLOW + Style.BRIGHT))
        print("Output:", msg, "\n", msg.output.decode("utf-8", errors="ignore"))
        ask_for_troubleshoot(troubleshoot)
        error("Python script didn't return properly!")
    except IOError as msg:
        print("Python script error:", msg)
        ask_for_troubleshoot(troubleshoot)
        error("Error during script execution")
    if CMD_ARGS.verbose:
        print(output.decode("utf-8", errors="ignore"))
    os.chdir(SETUP_DIR)

```
