### ISSUE TITLE
Interrogate: Unrecognized option '-nomangle'

### ISSUE THREAD

**Issue by DrLuke** [tobspr/RenderPipeline#93]
When building the C++ files during setup, interrogate fails because of an unrecognized argument.

```python setup.py                                                                                                                                                                            [1]
-------------------------------------------------------------------------------

Render Pipeline Setup 1.3

-------------------------------------------------------------------------------


[ 01 ]  Checking Panda3D Modules


[ 02 ]  Checking requirements ..
        Running script: data/setup/check_requirements.py


The C++ modules of the pipeline are faster and produce better 
results, but we will have to compile them. As alternative, 
a Python fallback is used, which is slower and produces worse 
results. Also some plugins only partially work with the python 
fallback (e.g. PSSM). Do you want to compile the C++ modules? (y/n): y


[ 03 ]  Downloading the module builder ...
        Running script: rpcore/native/update_module_builder.py


[ 04 ]  Building the native code .. (This might take a while!)
        Running script: rpcore/native/build.py




------------------------------------------------------------

CMake Error:


------------------------------------------------------------




Failed to execute 'build.py'
Output: Command '['/home/drluke/prog/pandarenderpipelinetest/pandarptest/venv/bin/python', '-B', 'build.py']' returned non-zero exit status 255. 
 Creating directory /home/drluke/prog/pandarenderpipelinetest/render_pipeline/rpcore/native/linux_amd64_panda1.10.0_py36
Executing command:  cmake /home/drluke/prog/pandarenderpipelinetest/render_pipeline/rpcore/native -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE:STRING=/home/drluke/prog/pandarenderpipelinetest/pandarptest/venv/bin/python -DPROJECT_NAME:STRING=native_ -DINTERROGATE_LIB:STRING=p3interrogatedb -DPYTHONVERDOT:STRING=3.6 -DTHIRDPARTY_WIN_DIR= -DHAVE_LIB_EIGEN=TRUE -DIGATE_VERBOSE=0 -DOPTIMIZE=3 

-- Could NOT find Panda (missing: PANDA_LIBRARIES) 
CMake Error at CMakeLists.txt:261 (message):
  Interrogate failed: Executing command: /usr/bin/interrogate -fnames -string
  -refcount -assert -python-native -S/usr/include/panda3d/parser-inc
  -S/usr/include/panda3d/ -srcdir .  -oc interrogate_wrapper.cpp -od
  interrogate.in -module native_ -library native_ -nomangle -DINTERROGATE
  -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -D__attribute__\(x\)=
  -D__i386__ ./ies_dataset.h ./internal_light_manager.h ./shadow_manager.h
  ./pssm_camera_rig.h ./gpu_command.h ./shadow_atlas.h ./tag_state_manager.h
  ./pointer_slot_storage.h ./pssm_helper.h ./gpu_command_list.h
  ./config_rsnative.h ./rp_point_light.h ./shadow_source.h ./rp_spot_light.h
  ./rp_light.h

  

  /usr/bin/interrogate: unrecognized option '-nomangle'

   Traceback (most recent call last):
    File "scripts/interrogate.py", line 135, in <module>
      interrogate()
    File "scripts/interrogate.py", line 108, in interrogate
      try_execute(*cmd)
    File "/home/drluke/prog/pandarenderpipelinetest/render_pipeline/rpcore/native/scripts/common.py", line 253, in try_execute
      raise Exception("Process had non-zero returncode:", process.returncode)

  Exception: ('Process had non-zero returncode:', 1)



-- Configuring incomplete, errors occurred!
See also "/home/drluke/prog/pandarenderpipelinetest/render_pipeline/rpcore/native/linux_amd64_panda1.10.0_py36/CMakeFiles/CMakeOutput.log".




It seems the setup failed, do you want to open the troubleshooting page for this step? (y/n): ```

**Comment by rdb** [comment]
You need to use a recent development build of Panda3D in order to use the RenderPipeline.

**Comment by DrLuke** [comment]
Do you mean a build that comes with the headers? The package I installed it from also installs headers. I'm running on Arch Linux and have version 1.9.4 of panda installed, which seems to be the newest.

**Comment by rdb** [comment]
No, by development build I mean one that is built from the `master` branch on GitHub, which will be a pre-release of 1.10.  The latest stable release (1.9.4) is too old for the RenderPipeline.

If you don't want to build Panda from source then you can install it with pip:
```
sudo pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d
```
